### ISSUE TITLE
About tags

### ISSUE THREAD

**Issue by Kakadu** [ocaml/opam.ocaml.org#12]
Documentation mentions tags field when describing opam file format. It will be great to have a link there to the page where all used tags are listed. For example, I want to add some tags to my opam package and I don't know which to use to be in sync with packages with related functionality (for example, should I write `gui` or `UI` and etc.)

**Comment by rjbou** [comment]
There is no allowed list of tags, it's upon package maintainers and/or opam repository maitnainers.
