### ISSUE TITLE
broken redirect

### ISSUE THREAD

**Issue by ygrek** [ocaml/opam.ocaml.org#19]
moving https://github.com/ocaml/opam-repository/issues/7804 to this repo

I would speculate that maybe https://github.com/ocaml/opam.ocaml.org/blob/master/nginx.conf#L39 should be changed to 
```
   rewrite ^/pkg/((?U).+)/(.+)    /packages/$1/$1.$2 permanent;
```

**Comment by rjbou** [comment]
Was already fixed on server, updated repo. Thanks!
