### ISSUE TITLE
make design consistent with ocaml.org

### ISSUE THREAD

**Issue by agarwal** [ocaml/opam.ocaml.org#2]
The opam subdomain is now very integrated into ocaml.org from an end-user perspective. Yaron reported in ocaml/ocaml.org#218 that it is jarring to have such a different design. Also, even within the opam subdomain, the front page and the pkg/ pages have a different design. Ideally, all of *.ocaml.org pages would use the main ocaml.org style sheets.

**Comment by rjbou** [comment]
Fixed with opam2web/pull/113
