### ISSUE TITLE
Link to public key does not work

### ISSUE THREAD

**Issue by bschommer** [ocaml/opam.ocaml.org#23]
The link [opam dev team ](https://opam.ocaml.org/opam-dev-pubkey.pgp) does not work and leads to an empty page.

**Comment by rjbou** [comment]
Thanks for noticing it! We'll put it back.
/cc @avsm

**Comment by bschommer** [comment]
Gentle ping, the link seems to still not work.

**Comment by erikmd** [comment]
Indeed, I can confirm the public key URL still raises a HTTP 404.

@avsm do you know when you'll be able to reinstate it?

It happens to be blocking on our side to be able to add [new base images in coq-community](https://github.com/coq-community/docker-base/) (with a verified opam binary).

BTW, I also tried to get the public key (to no avail) from:

* https://pgp.mit.edu (← based on [SKS](https://github.com/SKS-Keyserver/sks-keyserver))
* https://keys.openpgp.org (← based on [Sequoia-PGP](https://sequoia-pgp.org/))
* https://keyserver.ubuntu.com (← based on [Hockeypuck](https://hockeypuck.io/))

So you may also want at some point, to upload the public key to some of these three "standard" PGP keyservers?

**Comment by avsm** [comment]
We're just looking into how to track the key management. @dra27 @rjbou , would you be able to commit the public key into opam2web repo for now, so we can at least serve the current one?

**Comment by dra27** [comment]
Agreed! Let's do that for now to put the fire out and settle the wider question of key management (a little bit) later!

**Comment by bschommer** [comment]
Gentle ping, it seems the link is still broken.

**Comment by erikmd** [comment]
Hi all, could you have a look anew at this issue [which is blocking for us](https://github.com/coq-community/docker-base/pull/17)?

We still get a 404 for the link mentioned in https://github.com/ocaml/opam/releases :

```
$ curl -fsSL https://opam.ocaml.org/opam-dev-pubkey.pgp
curl: (22) The requested URL returned error: 404
```

@avsm @dra27 @rjbou, Cc @gares @Zimmi48 FYI

**Comment by dra27** [comment]
This is being looked at, yes - the correct (test) system is presently deployed at https://opam-3.ocaml.org and we're just in the process of getting the changes merged and deploying it to https://opam.ocaml.org

**Comment by gares** [comment]
Thanks!

**Comment by erikmd** [comment]
Thanks a lot @dra27! (Thanks to your heads-up we were able to rebuild our base images using the preview URL you mentioned.)

**Comment by dra27** [comment]
This is now deployed - https://opam.ocaml.org/opam-dev-pubkey.pgp can now be used again
