### ISSUE TITLE
`opam-dev-pubkey.pgp` seems unavailable (HTTP 404)

### ISSUE THREAD

**Issue by erikmd** [ocaml/opam.ocaml.org#24]
Hi! it seems the opam dev team public key (mentioned [in the releases](https://github.com/ocaml/opam/releases/tag/2.1.2)) is not available currently:

```
$ curl -fsSL https://opam.ocaml.org/opam-dev-pubkey.pgp
curl: (22) The requested URL returned error: 404
```

Would its URL have changed?

Cc @AltGr @rjbou

**Comment by rjbou** [comment]
Duplicate with #23
/cc @avsm
