### ISSUE TITLE
OpenPGP Key URL in tagged releases returs 404 Not Found

### ISSUE THREAD

**Issue by SchnWalter** [ocaml/opam.ocaml.org#25]
The OpenPGP key fingerpint mentioned in the release notes matches the released binaries, but the linked key returns a `404 Not Found` response. See:

> https://github.com/ocaml/opam/releases/tag/2.1.2

```
> curl -I https://opam.ocaml.org/opam-dev-pubkey.pgp
HTTP/2 404 
server: Caddy
date: Wed, 09 Feb 2022 20:15:06 GMT
```

**Comment by dra27** [comment]
This file is now available

**Comment by hannesm** [comment]
Not sure about that "This file is now available". I still get a 404 when attempting to download the URL above.

Maybe your "load balancing" approach does not ensure that different servers are synchronised? (as mentioned in https://discuss.ocaml.org/t/migration-opam-ocaml-org-moving-providers-this-week/11606)

From the opam release page (https://github.com/ocaml/opam/releases/tag/2.1.4) the URL mentioned is "https://opam-3.ocaml.org/opam-dev-pubkey.pgp" -- which indeed results in a OpenPGP key, but it expired on 2022-08-21.

**Comment by kit-ty-kate** [comment]
maybe it's just DNS taking some time to propagate, it was moved to the new server litterally 50 minutes ago. `curl -O https://opam.ocaml.org/opam-dev-pubkey.pgp` worked just fine for me.

**Comment by hannesm** [comment]
FWIW, the URL @kit-ty-kate mentions, `https://opam.ocaml.org/opam-dev-pubkey.pgp` returns an OpenPGP public key. This is great.

Unfortunately, it expired on 2022-08-21.
